version: 0.0
os: linux
files:
  - source: /
    destination: /root/
  
hooks:
  BeforeInstall:
    - location: /r.sh
      runas: root
      timeout: 100
    
#   AfterInstall:
#     - location: Scripts/RunResourceTests.sh
#       timeout: 180
#   ApplicationStart:
#     - location: Scripts/RunFunctionalTests.sh
#       timeout: 3600
#   ValidateService:
#     - location: Scripts/MonitorService.sh
#       timeout: 3600
#       runas: codedeployuser
