version: 0.0
os: linux
files:
        - source: /index.html
          destination: /var/www/html/
    # - source: source
    #  destination: /webapps/myApp
hooks:
      BeforeInstall:
        - location: /s.sh
        #- location: Scripts/UnzipDataBundle.sh
    #  AfterInstall:
    #    - location: Scripts/RunResourceTests.sh
    #      timeout: 180
    #  ApplicationStart:
    #    - location: Scripts/RunFunctionalTests.sh
    #      timeout: 3600
    #  ValidateService:
    #    - location: Scripts/MonitorService.sh
    #      timeout: 3600
    #      runas: codedeployuser

